# fly.toml app configuration file generated for gestion-eventos on 2023-08-07T21:10:44-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "gestion-eventos"
primary_region = "bog"

[build]

[http_service]
  internal_port = 3002
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
